#coded By R47uL

import os 

os.system("pkg up -y")
os.system("apt install python")
os.system("apt install git")
os.system("pip install pyfiglet")
os.system("termux-setup-storage")
os.system("apt install php -y")
os.system("apt install git -y")
os.system("apt install golang -y")
os.system("apt install host -y")
os.system("apt install nano -y")
os.system("apt install cmatrix -y")
os.system("apt install figlet -y")
os.system("apt install wget -y")
os.system("apt install toilet -y")
os.system("apt install cowsay -y")
os.system("apt install ruby -y")
os.system("gem install lolcat")
os.system("apt install curl -y")
os.system("apt install unzip -y")
os.system("apt install openssh -y")
os.system("apt install tor -y")
os.system("apt install net-tools -y")
os.system("apt install unrar -y")
os.system("apt install clang -y")
os.system("apt install w3m -y")
os.system("apt install proot -y")
os.system("pip install requests")
os.system("pip install mechanize")
os.system("pip install --upgrade pip")
os.system("pip2 install --upgrade pip")